### PR TITLE
Fix warning "Can't use 'defined(@array)" breaking the kernel build

### PR DESCRIPTION
**Pull request by citronalco**
This was also mentioned in https://github.com/rickgaiser/linux-dev/issues/1

### CODE REVIEW

**Comment by rickgaiser** [comment]
Since this is not a problem with the PS2 port, but with the linux kernel itself, have you tried looking for fixes in the mainline linux kernel? Perhaps we can simply cherry-pick those changes? That would also make rebasing to a newer linux kernel (3.10 for instance) more simple.

Have you tried this commit?:
https://github.com/torvalds/linux/commit/70730bca1331fc50c3caacaea00439de1325bd6e

**Comment by citronalco** [comment]
The change I did can be found on several mailing lists, so no, I did not look into mainline.
But https://github.com/torvalds/linux/commit/70730bca1331fc50c3caacaea00439de1325bd6e works, too, but does not apply cleanly.
I created another pull request for that - pick whatever you prefer :)

**Comment by rickgaiser** [comment]
Please use "git cherry-pick <commit_hash>" to apply the fix from upstream. If it does not apply cleanly then you'll need to solve the merge conflict first, then do a "git cherry-pick --continue". By doing it this way you will preserve the original author/description/date/time/etc...

There's no need to create a new pull request for each change, you can "git push" or "git push --force" the changes to this branch to keep the discussion in one place.

**Comment by rickgaiser** [comment]
I've updated both the ps2-v2.6.35.14 branch and the ps2-v3.8 branch. I have compile tested them both, as well as the changes buildroot. Could you test to see if it solves the problems you where having?

**Comment by citronalco** [comment]
Yes, Linux problems solved, thanks - also for pushing me to use git properly.
Did not check the new buildroot so far. At least linux-dev/config/buildrootconfig.txt needs an update.

**Comment by citronalco** [comment]
Buildroot works.

**Pull request closed without merging**
